-- Criar a tabela noivos
CREATE TABLE public.noivos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome_noivo VARCHAR(255) NOT NULL,
  nome_noiva VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefone VARCHAR(50) NOT NULL,
  criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Criar a tabela eventos (relacionado a noivos)
CREATE TABLE public.eventos (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  noivos_id BIGINT NOT NULL REFERENCES public.noivos(id) ON DELETE CASCADE,
  data_evento DATE NOT NULL,
  local VARCHAR(255) NOT NULL,
  descricao TEXT,
  orcamento DECIMAL(10, 2),
  criado_em TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
